### ISSUE TITLE
Compilation on UBUNTU 18.04.1 LTS fails

### ISSUE THREAD

**Issue by wohauser** [benoit-canet/charibefs#14]
Using latest from repository and a compiled and installed thrift-0.11.0.
I got following compile errors:
----
make
Scanning dependencies of target server_lib
[  8%] Building CXX object CMakeFiles/server_lib.dir/charybde_ops.cc.o
[ 16%] Building CXX object CMakeFiles/server_lib.dir/server.cc.o
/home/wohauser/tools/charybdefs/server.cc: In function ‘void server_thread()’:
/home/wohauser/tools/charybdefs/server.cc:259:43: error: variable ‘boost::shared_ptr<server_handler> handler’ has initializer but incomplete type
         shared_ptr<server_handler> handler(new server_handler());
                                           ^
/home/wohauser/tools/charybdefs/server.cc:260:41: error: variable ‘boost::shared_ptr<apache::thrift::TProcessor> processor’ has initializer but incomplete type
         shared_ptr<TProcessor> processor(new serverProcessor(handler));
                                         ^
/home/wohauser/tools/charybdefs/server.cc:261:53: error: variable ‘boost::shared_ptr<apache::thrift::transport::TServerTransport> serverTransport’ has initializer but incomplete type
         shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
                                                     ^
/home/wohauser/tools/charybdefs/server.cc:262:55: error: variable ‘boost::shared_ptr<apache::thrift::transport::TTransportFactory> transportFactory’ has initializer but incomplete type
         shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
                                                       ^
/home/wohauser/tools/charybdefs/server.cc:263:53: error: variable ‘boost::shared_ptr<apache::thrift::protocol::TProtocolFactory> protocolFactory’ has initializer but incomplete type
         shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());
                                                     ^
CMakeFiles/server_lib.dir/build.make:86: recipe for target 'CMakeFiles/server_lib.dir/server.cc.o' failed
make[2]: *** [CMakeFiles/server_lib.dir/server.cc.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/server_lib.dir/all' failed
make[1]: *** [CMakeFiles/server_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
----
Regards
Wolfgang Hauser

**Comment by syuu1228** [comment]
Not sure what's the difference, but my suggested way to build charybdefs on Ubuntu 16.04(https://github.com/syuu1228/charybdefs/commit/67d08de2c7e6b2196ff3d9c0c9795a082c0f73c8) also worked fine on Ubuntu 18.04.1 for me:
```
Scanning dependencies of target server_lib
[  8%] Building CXX object CMakeFiles/server_lib.dir/charybde_ops.cc.o
[ 16%] Building CXX object CMakeFiles/server_lib.dir/server.cc.o
[ 25%] Linking CXX static library libserver_lib.a
[ 25%] Built target server_lib
Scanning dependencies of target thrift
[WARNING:/home/syuu/charybdefs/server.thrift:16] No field key specified for method, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:19] No field key specified for methods, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:20] No field key specified for random, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:21] No field key specified for err_no, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:22] No field key specified for probability, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:23] No field key specified for regexp, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:24] No field key specified for kill_caller, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:25] No field key specified for delay_us, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:26] No field key specified for auto_delay, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:29] No field key specified for random, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:30] No field key specified for err_no, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:31] No field key specified for probability, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:32] No field key specified for regexp, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:33] No field key specified for kill_caller, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:34] No field key specified for delay_us, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:35] No field key specified for auto_delay, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:16] No field key specified for method, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:19] No field key specified for methods, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:20] No field key specified for random, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:21] No field key specified for err_no, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:22] No field key specified for probability, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:23] No field key specified for regexp, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:24] No field key specified for kill_caller, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:25] No field key specified for delay_us, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:26] No field key specified for auto_delay, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:29] No field key specified for random, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:30] No field key specified for err_no, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:31] No field key specified for probability, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:32] No field key specified for regexp, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:33] No field key specified for kill_caller, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:34] No field key specified for delay_us, resulting protocol may have conflicts or not be backwards compatible!

[WARNING:/home/syuu/charybdefs/server.thrift:35] No field key specified for auto_delay, resulting protocol may have conflicts or not be backwards compatible!

[ 25%] Built target thrift
Scanning dependencies of target charybde_lib
[ 33%] Building CXX object CMakeFiles/charybde_lib.dir/charybde_ops.cc.o
[ 41%] Building CXX object CMakeFiles/charybde_lib.dir/server.cc.o
[ 50%] Linking CXX static library libcharybde_lib.a
[ 50%] Built target charybde_lib
Scanning dependencies of target server
[ 58%] Building CXX object CMakeFiles/server.dir/gen-cpp/server_constants.cpp.o
[ 66%] Building CXX object CMakeFiles/server.dir/gen-cpp/server.cpp.o
[ 75%] Building CXX object CMakeFiles/server.dir/gen-cpp/server_types.cpp.o
[ 83%] Linking CXX static library libserver.a
[ 83%] Built target server
Scanning dependencies of target charybdefs
[ 91%] Building C object CMakeFiles/charybdefs.dir/charybdefs.c.o
[100%] Linking CXX executable charybdefs
[100%] Built target charybdefs
```

**Comment by bentsi** [comment]
fixed by #15
